---
title: "[개발일지]2021-01-08"
published: false
---

# 회고
오류를 수습하느라 시간을많이 소비했고, 배포 후 테스트를 하느라 시간을 많이 소비했다. 결국 해야할 작업을 거의 하지 못했다. 언제 unexpected 작업이 생길지 모르기 때문에 그날그날의 작업을 다 타이트하게라도 해 놓는 것이 중요한 것 같다. 더 중요한 것은 갑자기 들어온 unexpected 작업을  빠르게 해결하는 것 인 것 같다.
# 기억해야 할 내용
dev에서 `git pull` 을 했을 때 `Your branch is ahead of 'origin/dev' by 2 commits.` 이 떴다.
어제 origin을 롤백했었는데, origin은 롤백으로 인해 2개의 commit 이전으로 돌아가고, 2개의 commit이 반영된
최신 상태일거라는 추측을 했다. 아무튼 그래서 실행한 명령어는,   
```python
git fetch origin
git reset --hard origin/dev
```
**git fetch origin**   
원격 저장소의 commit 히스토리와 나의 로컬 commit 히스토리가 다르기 때문에, 원격 저장소의 데이터를 받아와 로컬 저장소를 업데이트 해줘야한다.   

**git reset --hard origin/dev**   
Git은 한 달 정도 분량의 commit 들을 시간 순서대로 저장 해놓는다.    
그렇기 때문에 `git reset --hard` 를 했을 때는, 시간 순으로 저장된 그 commit들 중 하나로 HEAD를 이동하는 것이다.
시간순서대로 저장된 commit들을 보는 명령어는` git reflog` .  
git reset과 비교가되는 명령어중에 `git revert` 가 있다. git reset과의 차이점은, git revert는 내부적으로 새로운 commit을 만들어 롤백한 이력까지 모두 기록이되어 비교적 안전한 방법이라는 것이다.   
공용 브랜치(origin)에서 reset을 했기 때문에, 나도 dev에서 `git reset --hard origin/dev`을 한 것이다.*(사실 공용 브랜치에서 reset은 지양하는 것이 좋다고한다.)*
